### ISSUE TITLE
Dependency issues building package from scratch

### ISSUE THREAD

**Issue by hannahker** [OCHA-DAP/gghdx#26]
I'm trying to follow [these instructions](https://github.com/OCHA-DAP/gghdx/pull/25#issuecomment-2103438273) and build this package locally by:
1. Cloning the repo
2. Opening the project in RStudio
3. `ctrl` + `shift` + `b` 

But get the following error: 

```
* installing to library '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library'
ERROR: dependencies 'dplyr', 'ggplot2', 'ggthemes', 'magrittr', 'purrr', 'rlang', 'showtext', 'sysfonts', 'tibble' are not available for package 'gghdx'
* removing '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/gghdx'

Exited with status 1.
```

I have a very fresh `R` install, so wondering if some of these dependencies need to be defined somewhere? Problem can be resolved if I manually install each package.

**Comment by caldwellst** [comment]
So all dependencies of an R package are defined in `DESCRIPTION`. Then you have to explicitly refer to them throughout package scripts in various ways, typically using `package::object` notation to reference the use of any dependency functions, datasets, or other exports. However, you cannot build a package without the dependencies installed. I saw what @zackarno recommended but not sure it works in the way described.

All of the shortcuts for building and installing and checking packages are available in the top right of RStudio, and are the same shortcuts used through the keyboard. In this case, `ctrl` + `shift` + `b` is the equivalent of `Build`.
<img width="359" alt="image" src="https://github.com/OCHA-DAP/gghdx/assets/8086547/cd38afda-6bf1-4d6a-bced-f8489c1bb4a1">

However, they are also accessible as functions in the `{devtools}` package, like `devtools::build()`, `devtools::install()`, etc. which are utilities for local development. Useful to know because they are well documented and if you need to troubleshoot on SO or elsewhere, easier to reference those functions directly. `devtools::build()` builds a package, either a source package library that resembles what should be submitted to CRAN, or a binary package that is just a tarball you or others can use to install from. However, it doesn't install that package locally.

For that, you want to use `devtools::install()` which automatically installs the local package from any project you're working in, in this case. The `install()` function, like `install.packages()` also automatically installs any missing dependencies, so that will also solve your issue, as I don't think `build()` is designed to install dependencies if they aren't already present.

**Comment by caldwellst** [comment]
Oh, and to add, I think the easiest way to locally test is to just use `devtools::load_all()` (which will require you to have the package dependencies installed already). It simply loads all of the functions locally in to your environment and if you make a change to any function as you develop, you just rerun `devtools::load_all()`! The shortcut I use `cmd` + `shift`+ `L`.

**Comment by zackarno** [comment]
oh nice thats interesting!  Guess i've always just been using the `build` workflow from the context of being a package developer with all dependencies already installed without realizing it.
